FROM ghcr.io/codysk/bgmi-all-in-one-base:1.7  AS test-env
MAINTAINER me@iskywind.com

ENV LANG=C.UTF-8 BGMI_PATH="/bgmi/conf/bgmi"
ADD ./ /home/bgmi-docker
WORKDIR /home/bgmi-docker/BGmi

RUN apk add --update g++

ENV POETRY_HOME=/opt/poetry
ENV PATH=$POETRY_HOME/bin:$PATH

# RUN curl -sSL https://install.python-poetry.org | python3 - || cat *.log
RUN python3 -m venv $POETRY_HOME && \
	$POETRY_HOME/bin/pip install /wheelhouse/*.whl && \
	$POETRY_HOME/bin/pip install poetry
RUN sh -c 'poetry install -vvv --with dev || cat *.log' && \
	source $(poetry env info --path)/bin/activate && \
	coverage run -a -m bgmi install && \
	bgmi --help && \
	coverage run -a -m pytest tests --cache-requests --ignore=tests/downloader
