FROM ghcr.io/codysk/bgmi-all-in-one-base:1.3  AS test-env
MAINTAINER me@iskywind.com

ENV LANG=C.UTF-8 BGMI_PATH="/bgmi/conf/bgmi"
ADD ./ /home/bgmi-docker
WORKDIR /home/bgmi-docker/BGmi

RUN curl -sSL https://install.python-poetry.org | python3 - || cat *.log
RUN export PATH="/root/.local/bin:$PATH" && \
	sh -c 'poetry install -vvv --with dev || cat *.log' && \
	source $(poetry env info --path)/bin/activate && \
	coverage run -a -m bgmi.main install && \
	bgmi -h && \
	coverage run -a -m pytest tests \
            --cache-requests --reruns=2 --reruns-delay=1 --maxfail=2 \
            --ignore=tests/downloader
